/**
 * Emits SQL to seed public.players from Wikipedia's 2026 World Cup squads page.
 *
 * Usage:
 *   bun run scripts/gen-players-wiki-sql.ts > /tmp/players.sql
 */
import { WC_TEAMS } from '../src/data/worldCup2026'

const WIKI_API =
  'https://en.wikipedia.org/w/api.php?action=parse&page=2026_FIFA_World_Cup_squads&prop=wikitext&format=json'

type SquadRow = {
  fifaCode: string
  number: number
  position: 'GK' | 'DEF' | 'MID' | 'FWD'
  name: string
}

const POS: Record<string, SquadRow['position']> = {
  GK: 'GK',
  DF: 'DEF',
  MF: 'MID',
  FW: 'FWD',
  DEF: 'DEF',
  MID: 'MID',
  FWD: 'FWD',
}

const esc = (s: string) => s.replaceAll("'", "''")

function normalizeLabel(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&amp;/gi, ' and ')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

function cleanName(raw: string): string {
  return raw
    .replace(/<ref[^>]*>.*?<\/ref>/gis, '')
    .replace(/<ref[^/>]*\/>/gi, '')
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2')
    .replace(/\[\[([^\]]+)\]\]/g, '$1')
    .replace(/\{\{.*?\}\}/g, '')
    .replace(/''/g, '')
    .replace(/&nbsp;/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function param(block: string, key: string): string | null {
  const rx = new RegExp(
    `\\|\\s*${key}\\s*=\\s*([\\s\\S]*?)(?=\\|\\s*[a-z_]+\\s*=|$)`,
    'i',
  )
  const m = block.match(rx)
  return m?.[1]?.trim() ?? null
}

function extractRows(wikitext: string): SquadRow[] {
  const teamsByName = new Map<string, string>()
  for (const t of WC_TEAMS) teamsByName.set(normalizeLabel(t.name), t.fifaCode)

  // Common heading aliases used in Wikipedia pages.
  teamsByName.set(normalizeLabel('South Korea'), 'KOR')
  teamsByName.set(normalizeLabel("Cote d'Ivoire"), 'CIV')
  teamsByName.set(normalizeLabel('Cote d Ivoire'), 'CIV')
  teamsByName.set(normalizeLabel('DR Congo'), 'COD')
  teamsByName.set(normalizeLabel('DRC'), 'COD')
  teamsByName.set(normalizeLabel('Democratic Republic of Congo'), 'COD')

  const headingRx = /^===\s*([^=\n]+?)\s*===\s*$/gm
  const headings: Array<{ title: string; start: number; bodyStart: number }> = []
  let hm: RegExpExecArray | null
  while ((hm = headingRx.exec(wikitext)) !== null) {
    headings.push({
      title: hm[1].trim(),
      start: hm.index,
      bodyStart: headingRx.lastIndex,
    })
  }

  const rows: SquadRow[] = []
  for (let i = 0; i < headings.length; i++) {
    const h = headings[i]
    const fifaCode = teamsByName.get(normalizeLabel(h.title))
    if (!fifaCode) continue

    const nextStart = i + 1 < headings.length ? headings[i + 1].start : wikitext.length
    const section = wikitext.slice(h.bodyStart, nextStart)
    const playerRx = /\{\{nat fs g player\|([\s\S]*?)\}\}/g
    let pm: RegExpExecArray | null
    while ((pm = playerRx.exec(section)) !== null) {
      const block = `|${pm[1]}`
      const noRaw = param(block, 'no')
      const posRaw = (param(block, 'pos') ?? '').toUpperCase()
      const nameRaw = param(block, 'name')
      if (!noRaw || !nameRaw) continue

      const number = Number.parseInt(noRaw, 10)
      const position = POS[posRaw]
      const name = cleanName(nameRaw)
      if (!Number.isFinite(number) || !position || !name) continue

      rows.push({ fifaCode, number, position, name })
    }
  }

  return rows
}

async function main() {
  const res = await fetch(WIKI_API, {
    headers: {
      'User-Agent': 'score26-seeder/1.0 (local dev setup)',
      Accept: 'application/json',
    },
  })
  if (!res.ok) {
    throw new Error(`Wikipedia API request failed: ${res.status}`)
  }

  const json = (await res.json()) as {
    parse?: { wikitext?: { '*': string } }
  }
  const wikitext = json.parse?.wikitext?.['*']
  if (!wikitext) {
    throw new Error('Could not read squads wikitext from Wikipedia response')
  }

  const rows = extractRows(wikitext)
  if (rows.length === 0) {
    throw new Error('Parsed 0 players from Wikipedia squads page')
  }

  const byTeam = new Map<string, number>()
  for (const r of rows) byTeam.set(r.fifaCode, (byTeam.get(r.fifaCode) ?? 0) + 1)

  const lines: string[] = []
  lines.push('-- AUTO-GENERATED by scripts/gen-players-wiki-sql.ts — do not edit by hand.')
  lines.push('-- Source: https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads')
  lines.push('begin;')
  lines.push('truncate table public.players restart identity;')

  const values = rows
    .map(
      (r) =>
        `((select id from public.teams where fifa_code = '${esc(r.fifaCode)}'), '${esc(
          r.fifaCode,
        )}', ${r.number}, '${r.position}', '${esc(r.name)}', null)`,
    )
    .join(',\n  ')

  lines.push('insert into public.players (team_id, fifa_code, number, position, name, photo) values')
  lines.push(`  ${values};`)
  lines.push('commit;')

  // Metadata comment block (useful when reviewing generated SQL files).
  lines.push(`-- Parsed players: ${rows.length}`)
  lines.push(
    `-- Teams parsed: ${[...byTeam.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `${k}=${v}`)
      .join(', ')}`,
  )

  console.log(lines.join('\n'))
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err))
  process.exit(1)
})
