/**
 * Emits SQL to seed a DB `matches` fixtures table + team flag emojis, reusing the
 * frontend's own fixture/kickoff logic (single source of truth). Run:
 *   bun run scripts/gen-fixtures-sql.ts > /tmp/fixtures.sql
 */
import { getMatches } from '../src/data/matches'
import { WC_MATCHES, wcStadiumById } from '../src/data/worldCup2026'
import { ALL_TEAMS } from '../src/data/teams'

const wcById = new Map(WC_MATCHES.map((m) => [m.id, m]))
const esc = (s: string) => s.replace(/'/g, "''")

const matchRows = getMatches().map((m) => {
  const wc = wcById.get(Number(m.id))!
  const localTime = (wc.kickoff ?? 'T00:00').split('T')[1].slice(0, 5) // venue-local HH:mm
  const stad = wcStadiumById.get(wc.stadiumId)
  const city = stad?.city ?? m.venue.split(', ').slice(-1)[0]
  return {
    id: Number(m.id),
    home_code: m.home.code,
    away_code: m.away.code,
    kickoff_utc: m.kickoff,
    city,
    local_time: localTime,
  }
})

const teamRows = ALL_TEAMS.map((t) => ({ code: t.code, emoji: t.flag }))

const lines: string[] = []
lines.push('-- AUTO-GENERATED by scripts/gen-fixtures-sql.ts — do not edit by hand.')
lines.push('alter table public.teams add column if not exists emoji text;')
for (const t of teamRows) {
  lines.push(
    `update public.teams set emoji = '${esc(t.emoji)}' where fifa_code = '${esc(t.code)}';`,
  )
}
lines.push('')
lines.push(`create table if not exists public.matches (
  id integer primary key,
  home_code text not null,
  away_code text not null,
  kickoff_utc timestamptz not null,
  city text,
  local_time text,
  created_at timestamptz not null default now()
);`)
lines.push('alter table public.matches enable row level security;')
lines.push(`do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='matches' and policyname='matches read') then
    create policy "matches read" on public.matches for select using (true);
  end if;
end $$;`)
lines.push('create index if not exists matches_kickoff_idx on public.matches (kickoff_utc);')

const values = matchRows
  .map(
    (m) =>
      `(${m.id}, '${esc(m.home_code)}', '${esc(m.away_code)}', '${m.kickoff_utc}', '${esc(
        m.city,
      )}', '${esc(m.local_time)}')`,
  )
  .join(',\n  ')
lines.push(`insert into public.matches (id, home_code, away_code, kickoff_utc, city, local_time) values
  ${values}
on conflict (id) do update set
  home_code = excluded.home_code,
  away_code = excluded.away_code,
  kickoff_utc = excluded.kickoff_utc,
  city = excluded.city,
  local_time = excluded.local_time;`)

console.log(lines.join('\n'))
